name: andariego_dart
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartz: ^0.10.0-nullsafety.1
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  freezed_annotation: ^2.0.1
  http: ^0.13.3
  json_annotation: null
  kt_dart: ^0.10.0
  logger: ^1.1.0

dev_dependencies:
  build_runner: null
  freezed: ^2.0.2
  json_serializable: null
  lints: ^2.0.0
  pedantic: ^1.11.0
